version: "3.8"

services:
  app:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_NAME=collegegram_dev
      - DB_USER=college_admin
      - DB_PASS=eAA<4v|15iX
      - SECRET_KEY=fBB>5w&26jY
      - CLIENT_URL=https://cherry-ring.dev1403.rahnemacollege.ir
      - API_URL=https://cherry-ring.dev1403.rahnemacollege.ir
      - PORT=4000
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USERNAME=collegegram.cherryring@gmail.com
      - MAIL_PASS="pirc itsz ljco cdhj"

    volumes:
      - ./src:/src
      - /var/www/collegegram/frontend/uploads:/app/uploads

    restart: on-failure

  db:
    image: hub.hamdocker.ir/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: oxe6y3sGTQQjXPP
      MYSQL_DATABASE: collegegram_dev
      MYSQL_USER: college_admin
      MYSQL_PASSWORD: eAA<4v|15iX
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
